# Generated by Django 3.2.4 on 2021-06-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_name',
            field=models.CharField(blank=True, choices=[('ofice1', 'office1'), ('ofice2', 'office2'), ('ofice3', 'office3')], max_length=100, null=True),
        ),
    ]
