# Generated by Django 3.2.4 on 2021-06-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210621_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remittance',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='remittance'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='revenue'),
        ),
    ]
